spring:
  datasource:
    username: sengard
    password: Sengard4167
    url: jdbc:mysql://localhost:3306/dbProject?UseSSL=false
  jpa:
    hibernate:
      ddl-auto: update
  resources:
    static-locations: classpath:/static/js